### ISSUE TITLE
Brocoli seems stuck after a network error

### ISSUE THREAD

**Issue by dbenaben** [mesocentre-mcia/brocoli#22]
After a network outage or an error during transfer, a window appears "Could not receive server response".
All is fine but click on "OK" button doesn't seem to have an effect (brocoli is stuck).
Maybe this is due to the amount of data (100GB/500GB) ?

**Comment by pigay** [comment]
I think that brocoli is not really stuck (at least in my tests). The progress bar is just hanging around but you can close it and still use brocoli.

**Comment by pigay** [comment]
progress bar will disappear even when an exception is raised.
